name: Build
on:
  schedule:
    - cron: '0 0 * * SUN'
  workflow_dispatch:
  merge_group:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - .gitignore
      - 'docs/**'
      - 'theme/**'
      - 'po/**'
      - book.toml
      - .github/workflows/docs.yaml
      - container/Dockerfile
      - .github/workflows/deploy-image.yml
  pull_request:
    paths-ignore:
      - '**.md'
      - .gitignore
      - 'docs/**'
      - 'theme/**'
      - 'po/**'
      - book.toml
      - .github/workflows/docs.yaml
      - container/Dockerfile
      - .github/workflows/deploy-image.yml

jobs:
  build_u-boot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets: [ u-boot ]
        profiles: [ latest ]
    steps:
      - name: Build
        uses: radxa-repo/bsp@main
        with:
          target: ${{ matrix.targets }}
          edition: ${{ matrix.profiles }}
          artifacts: true
